// lib/domain/entities/cell.dart
import 'package:freezed_annotation/freezed_annotation.dart';

part 'cell.freezed.dart'; // Generated by freezed
part 'cell.g.dart';

/// Represents a single cell on the chessboard with its row and column coordinates.
@freezed
abstract class Cell with _$Cell {
  const factory Cell({
    required int row, // Row index (0-7)
    required int col, // Column index (0-7)
  }) = _Cell;

  /// Checks if the cell coordinates are within the valid 8x8 board boundaries.
  // bool isValid() => row >= 0 && row < 8 && col >= 0 && col < 8;

  factory Cell.fromJson(Map<String, dynamic> json) => _$CellFromJson(json);
}

extension CellValidate on Cell {
  bool isValid() => row >= 0 && row < 8 && col >= 0 && col < 8;
}

extension CellColor on Cell {
  /// يتحقق مما إذا كانت الخلية ذات لون فاتح (أبيض) أو داكن (أسود).
  /// تُستخدم لتحديد لون مربع الأسقف.
  bool isLightSquare() => (row + col) % 2 == 0;
  bool isDarkSquare() => (row + col) % 2 != 0;
}
