// lib/domain/entities/move.dart
// ignore_for_file: invalid_annotation_target

import 'package:freezed_annotation/freezed_annotation.dart';

import 'cell.dart';
import 'piece.dart'; // Needed for PieceType in promotion

part 'move.freezed.dart'; // Generated by freezed
part 'move.g.dart'; // Generated by freezed

/// Represents a single move in the chess game.
@freezed
abstract class Move with _$Move {
  const factory Move({
    required Cell start, // Starting cell of the piece
    required Cell end, // Ending cell of the piece
    @Default(false) bool isCapture, // True if this move is a capture
    @Default(false) bool isCastling, // True if this move is castling
    @Default(false)
    bool isEnPassant, // True if this move is an en passant capture
    @Default(false) bool isPromotion, // True if this move is a pawn promotion
    PieceType?
    promotedPieceType, // The type of piece the pawn promotes to (if isPromotion is true)
    @Default(false)
    bool
    isTwoStepPawnMove, // True if a pawn moved two squares (for en passant tracking)
    required Piece movedPiece,
    Piece? capturedPiece,
    Piece? promotedTo,
    // Cell? enPassantTargetBefore,
    // bool? wasFirstMoveKing,
    // bool? wasFirstMoveRook,
    int? halfMoveClockBefore,
    int? fullMoveNumberBefore,
    // Cell? castlingRookFrom,
    // Cell? castlingRookTo,
    // === Reversible payload for fast unMake (ignored by JSON) ===
    // @JsonKey(ignore: true) Piece? capturedPiece,
    @JsonKey(ignore: true) Cell? capturedCell,
    @JsonKey(ignore: true) Piece? movedPieceBefore,

    // Castling rook info
    @JsonKey(ignore: true) Cell? rookFrom,
    @JsonKey(ignore: true) Cell? rookTo,
    @JsonKey(ignore: true) Piece? rookBefore,

    // Snapshot of prior board state
    @JsonKey(ignore: true)
    Map<PieceColor, Map<CastlingSide, bool>>? previousCastlingRights,
    @JsonKey(ignore: true) Cell? previousEnPassantTarget,
    @JsonKey(ignore: true) int? previousHalfMoveClock,
    @JsonKey(ignore: true) int? previousFullMoveNumber,
    @JsonKey(ignore: true) Map<PieceColor, Cell>? previousKingPositions,
    @JsonKey(ignore: true) int? previousZobristKey,
  }) = _Move;

  factory Move.fromJson(Map<String, dynamic> json) => _$MoveFromJson(json);
}
